name: CI (Push)

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build artifacts
        uses: gradle/gradle-build-action@v2
        id: build_app
        with:
          gradle-version: current
          generate-job-summary: true
          arguments: assembleRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename APKs
        run: |
          for f in wallet/build/outputs/apk/*/release/*.apk;
          do
            mv "$f" "$(echo "$f" | sed s/release-unsigned/release/)";
          done
      - name: Sign prod app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_prod
        with:
          releaseDirectory: wallet/build/outputs/apk/prod/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Sign dev app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_dev
        with:
          releaseDirectory: wallet/build/outputs/apk/dev/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: Signed Litecoin Wallet App
          path: ${{ steps.sign_app_prod.outputs.signedReleaseFile }}
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Signed Litecoin Testnet Wallet App
          path: ${{ steps.sign_app_dev.outputs.signedReleaseFile }}
          if-no-files-found: error
